export const API_ERROR = "EVENT/API_ERROR_RECEIVED";
export const WEATHER_DATA_RECEIVED = "EVENT/WEATHER_DATA_RECEIVED";
export const TUBING_PRESSURE_DATA_RECEIVED = "EVENT/TUBING_PRESSURE_DATA_RECEIVED";
export const TIME_DATA_RECEIVED = "EVENT/TIME_DATA_RECEIVED";
export const MEASUREMENT_TYPE_SELECT = "EVENT/MEASUREMENT_TYPE_SELECTED";